spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ce-82263409-sa-psql.postgres.database.azure.com:5432/postgres
    username: ktds
    password: Ktds!1234
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      # mode: always
      mode: embedded

server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

pvc:
  path: /mnt/todo
